### ISSUE TITLE
Determine Communication Channels

### ISSUE THREAD

**Issue by Pertempto** [el-apps/.github#2]
Communication is one of the most important things for a team/project to run well. We need to define our communication channels

**Comment by Pertempto** [comment]
We hopefully will have about one face-to-face meeting per week with Thursday lunches. But what can we use for online communication?

Slack would be a good option to start, since we're familiar with it. The free option is annoying cuz the history cuts off after 90 days.

Maybe there are some open source options that wouldn't be so limited? We don't want to pick something that is too techy, otherwise it might limit our ability to onboard more people to the team in the future.

**Comment by Pertempto** [comment]
Really, if we want transparency to be one of our core values, we could just keep most of our communication on GitHub in the issues and discussions.

**Comment by Pertempto** [comment]
In that case Slack would be a fine option, because any long-term historical communication should stay on GitHub

**Comment by DavidLandes** [comment]
> We hopefully will have about one face-to-face meeting per week with Thursday lunches. But what can we use for online communication?
> 
> Slack would be a good option to start, since we're familiar with it. The free option is annoying cuz the history cuts off after 90 days.
> 
> Maybe there are some open source options that wouldn't be so limited? We don't want to pick something that is too techy, otherwise it might limit our ability to onboard more people to the team in the future.

We could look at Discord. There's a real benefit to having separate channels to organize the discussions & I don't think Discord will cut off chat history.

**Comment by DavidLandes** [comment]
We really just need some way to organize the ideas & talk through basic details & feasibility, then once there's a project or issues on Github we can work out the details.

The way I see it is that Slack/Discord would filter out the bad ideas & facilitate good ideas. Then the good ideas can be brought over to Github

**Comment by Pertempto** [comment]
> We could look at Discord. There's a real benefit to having separate channels to organize the discussions & I don't think Discord will cut off chat history.

Sounds good to me. Do you want to set that up?

**Comment by DavidLandes** [comment]
https://discord.com/invite/GKwN2kez
